---

- name: Add group
  ansible.builtin.group:
    name: node_exporter
    state: present
    system: true

- name: Add user
  ansible.builtin.user:
    name: node_exporter
    state: present
    system: true
    shell: /sbin/nologin
    createhome: false

# Add a check here in the future so we don't run these tasks if we are already on the same version
# -----
- name: Create temporary download directory
  ansible.builtin.tempfile:
    state: directory
  register: temp_dir

- name: Download archive
  ansible.builtin.get_url:
    url: "https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_version }}/node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz"
    dest: "{{ temp_dir['path'] }}"
    checksum: "{{ node_exporter_checksum }}"

- name: Extract archive
  ansible.builtin.unarchive:
    src: "{{ temp_dir['path'] }}/node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz"
    dest: "{{ temp_dir['path'] }}"
    remote_src: true

- name: Copy binary
  ansible.builtin.copy:
    src: "{{ temp_dir['path'] }}/node_exporter-{{ node_exporter_version }}.linux-amd64/node_exporter"
    dest: "/usr/local/bin/node_exporter"
    owner: root
    group: root
    mode: 0755
    remote_src: true

- name: Remove temporary download directory
  ansible.builtin.file:
    path: "{{ temp_dir['path'] }}"
    state: absent
# -----

- name: Copy systemd unit file
  ansible.builtin.copy:
    src: node-exporter.service
    dest: /etc/systemd/system/node-exporter.service
  notify:
   - restart node-exporter

- name: Start and enable service
  ansible.builtin.service:
    name: node-exporter
    state: started
    enabled: yes
