---
# https://gist.github.com/JPvRiel/b7c185833da32631fa6ce65b40836887

- name: Create journal directory
  ansible.builtin.file:
    path: /var/log/journal
    state: directory
  register: create_journal_dir

- name: Create systemd tmpfiles
  ansible.builtin.command:
    cmd: /usr/bin/systemd-tmpfiles --create --prefix /var/log/journal
  when: create_journal_dir.changed

- name: Send SIGUSR1 to systemd-journald
  ansible.builtin.command:
    cmd: /usr/bin/killall -USR1 systemd-journald
  when: create_journal_dir.changed
