---

# https://computingforgeeks.com/how-to-install-prometheus-on-rhel-8/

- name: Add group
  ansible.builtin.group:
    name: prometheus
    state: present
    system: true

- name: Add user
  ansible.builtin.user:
    name: prometheus
    state: present
    system: true
    shell: /sbin/nologin
    createhome: false

- name: Create data and configuration directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: prometheus
    group: prometheus
  loop:
    - /var/lib/prometheus
    - /etc/prometheus

# Add a check here in the future so we don't run these tasks if we are already on the same version
# -----
- name: Create temporary download directory
  ansible.builtin.tempfile:
    state: directory
  register: temp_dir

- name: Download archive
  ansible.builtin.get_url:
    url: "https://github.com/prometheus/prometheus/releases/download/v{{ prometheus_version }}/prometheus-{{ prometheus_version }}.linux-amd64.tar.gz"
    dest: "{{ temp_dir['path'] }}"
    checksum: "{{ prometheus_checksum }}"

- name: Extract archive
  ansible.builtin.unarchive:
    src: "{{ temp_dir['path'] }}/prometheus-{{ prometheus_version }}.linux-amd64.tar.gz"
    dest: "{{ temp_dir['path'] }}"
    remote_src: true

- name: Copy binaries
  ansible.builtin.copy:
    src: "{{ temp_dir['path'] }}/prometheus-{{ prometheus_version }}.linux-amd64/{{ item }}"
    dest: /usr/local/bin
    owner: root
    group: root
    mode: 0755
    remote_src: true
  loop:
    - prometheus
    - promtool
  notify:
    - restart prometheus

- name: Copy files for console
  ansible.builtin.copy:
    src: "{{ temp_dir['path'] }}/prometheus-{{ prometheus_version }}.linux-amd64/{{ item }}"
    dest: /etc/prometheus
    owner: prometheus
    group: prometheus
    remote_src: true
  loop:
    - consoles
    - console_libraries
  notify:
    - restart prometheus

- name: Remove temporary download directory
  ansible.builtin.file:
    path: "{{ temp_dir['path'] }}"
    state: absent
# -----

- name: Copy configuration file
  ansible.builtin.template:
    src: prometheus.yml.j2
    dest: /etc/prometheus/prometheus.yml
    owner: prometheus
    group: prometheus
  notify:
    - restart prometheus

- name: Copy systemd unit file
  ansible.builtin.template:
    src: prometheus.service.j2
    dest: /etc/systemd/system/prometheus.service
  notify:
   - restart prometheus

- name: Start and enable service
  ansible.builtin.service:
    name: prometheus
    state: started
    enabled: yes
