Vagrant.configure("2") do |config|
  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.box = "generic/rocky9"

  config.vm.provider "virtualbox" do |v|
    v.memory = 2048
    v.cpus = 2
  end

  # Ansible control node
  config.vm.define "ansible", primary: true do |ansible|
    ansible.vm.hostname = "ansible"
    ansible.vm.network "private_network", ip: "192.168.123.10"
    ansible.vm.synced_folder "ansible/", "/home/vagrant/ansible",
      mount_options: ["dmode=755,fmode=644"]

    ansible.vm.provision "file", source: "keys/vagrant_lab",
      destination: "/home/vagrant/.ssh/id_rsa"

    ansible.vm.provision "shell", inline: <<-SCRIPT
      sudo dnf -y install python3-pip
      sudo python3 -m pip install ansible
    SCRIPT
    ansible.vm.provision "shell", inline: "chmod 400 /home/vagrant/.ssh/id_rsa"

    ansible.vm.provider "virtualbox" do |v|
      v.memory = 1024
    end
  end

  # Create lab VMs
  # The IP assignment is very ugly but just keep it simple since we don't need that many VMs
  # Make sure to manually update the inventory file if you add or remove VMs to the array below
  vms = ["lab01", "lab02"]

  vms.each_with_index do |name, index|
    config.vm.define name do |lab|
      lab.vm.hostname = name
      lab.vm.network "private_network", ip: "192.168.123.1#{index + 1}"

      lab.vm.provision "file", source: "keys/vagrant_lab.pub",
        destination: "/home/vagrant/.ssh/vagrant_lab.pub"

      lab.vm.provision "shell",
        inline: "cat /home/vagrant/.ssh/vagrant_lab.pub >> /home/vagrant/.ssh/authorized_keys"
    end
  end
end
